;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        exit-recursive-edit
        handle-switch-frame
        keyboard-escape-quit
        lsp-ui-mode
        ))

(setq mc/cmds-to-run-once
      '(
        ignore-preserving-kill-region
        kill-region
        load-file
        lsp-format-buffer
        lsp-ui-doc--handle-mouse-movement
        rust-check
        ))
